# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_QuantileSearch <- function(x, w, q, sw, n) {
    .Call('_Datavar_rcpp_QuantileSearch', PACKAGE = 'Datavar', x, w, q, sw, n)
}

